### ISSUE TITLE
IllegalArgumentException No implementation of method: :resolve-object of protocol: #'clj-jgit.internal/Resolvable found for class: nil

### ISSUE THREAD

**Issue by jaydeesimon** [clj-jgit/clj-jgit#42]
`IllegalArgumentException No implementation of method: :resolve-object of protocol: #'clj-jgit.internal/Resolvable found for class: nil  clojure.core/-cache-protocol-fn (core_deftype.clj:568)`

When trying to do a git-clone-full on an empty repository (no changes have been pushed to it yet) I get the above error. I could attempt a fix but wanted to get your thoughts. Thank you.

**Comment by jaydeesimon** [comment]
I looked into it a little bit more. I think the problem happens on the merge after the fetch. The repo has no commit-refs yet and ends up calling resolve-object on (first (.getAdvertisedRefs fetch-result)) which returns nil.

**Comment by edannenberg** [comment]
Thanks for the PR! Confirming it works as expected now.
