### ISSUE TITLE
The readme demo code does not work for me

### ISSUE THREAD

**Issue by jave** [clj-jgit/clj-jgit#44]
clj-jgit.porcelain=> (def my-repo  (git-clone-full "https://github.com/clj-jgit/clj-jgit.git" "local-folder2/clj-jgit"))
#'clj-jgit.porcelain/my-repo
clj-jgit.porcelain=> (git-log my-repo)

ClassCastException clojure.lang.PersistentArrayMap cannot be cast to org.eclipse.jgit.api.Git  clj-jgit.porcelain/git-log (porcelain.clj:352)

Some more data:
- I have tried various forks of clj-jgit, all exhibit the same problem
- I tried using different clojure versions, all give me the same problem
- I tried other things than git-log, all the same

Maybe I'm doing something fundamentally wrong, but I'm not sure what that would be. 

Any hints would be appreciated.

**Comment by jave** [comment]
Ok, so if I "load" the newly created repo, the demo code starts working.

like this:

clj-jgit-test.core=> (ns clj-jgit-test.core
  (:use 
        [clj-jgit.porcelain]
        )
  )
(def my-repo  (git-clone-full "https://github.com/clj-jgit/clj-jgit.git" "local-folder/clj-jgit"))

operations on my-repo do not work.

(def my-repo (load-repo "local-folder/clj-jgit"))

now operations work!

(git-status my-repo)

**Comment by edannenberg** [comment]
Thanks for the report! The `git-clone-full` functions actually returns a `jgit` repository object, it is however inside a map along with some other information. So the following will also work:

```clj
(def my-repo (:repo (git-clone-full ....)))
```
Updated the docs accordingly.
