### ISSUE TITLE
using ssh uri with keys 

### ISSUE THREAD

**Issue by jaromil** [clj-jgit/clj-jgit#45]
Hi there, I am trying to clone a git repository using ssh keys without success. Hope anyone can help as there is no documentation about this. Reading the code I came to this set of commands:

```clj
(:require [clj-jgit.porcelain :refer :all])
;; ...
        (binding [*ssh-identity-name* "git"] *ssh-identity-name*)
        (binding [*ssh-pubkey* (slurp (io/file "ssh.key.pub"))] *ssh-pubkey*)
        (binding [*ssh-prvkey* (slurp (io/file "ssh.key"))] *ssh-prvkey*)
        (binding [*ssh-passphrase* "XXX"] *ssh-passphrase*)
                (git-clone-full "ssh://git@github.com/dyne/zuper" "zuper"))))
```
I have also tried with url `ssh://git@github.com:dyne/zuper` without success. Any insight?

**Comment by jaromil** [comment]
Ok, found the solution using `with-identity` thanks to PR #40 for the hint. The correct code is then:

```clj

(with-identity {:name (slurp "ssh.key")
                :private (slurp "ssh.key")
                :public  (slurp "ssh.key.pub")
                :passphrase "XXX"
                :exclusive true}
  (git-clone "ssh://git@github.com/dyne/zuper" "zuper"))]))))
```

**Comment by edannenberg** [comment]
I added a small section regarding authentication to the `README.md`. Was about to add your example but slurping `ssh.key` twice seemed a bit odd so I wanted to double check first, is this really required?

**Comment by jaromil** [comment]
yea I know, but it is really required unless we change the underlying code. At the time of posting this I wasn't thinking of fixing clj-jgit but just finding out how to make it work. Now perhaps we can correct the logic behind requirements of values in this map with some implicit defaults...

**Comment by edannenberg** [comment]
I see, didn't really dive into that section yet as we just use the current user's ssh key. Fixing this sounds good to me, would you be interested in putting a PR together?

**Comment by edannenberg** [comment]
Since the switch to Apache Mina the configuration should hopefully be more intuitive:

```
(with-identity {:name "my.key" :key-dir "/some/path" pw: "$ecRet" :trust-all? true}
  (git-push my-repo :tags true))
```
