### ISSUE TITLE
git-clone using ssh with password

### ISSUE THREAD

**Issue by olliesweez** [clj-jgit/clj-jgit#51]
Hello, I am trying to clone a git repository through ssh using my username and password but am continuously getting a `FileNotFoundException`.
I have tried:
`(with-credentials "username" "password" (git-clone-full "ssh://username@server/path.git"))`
both with and without username in the uri.

and also:
`(with-identity {:passphrase "password"} (git-clone-full "ssh://username@server/path.git"))`

Since it doesn't seem obvious (to me) it could be useful to add an example of this use case to the readme.
This is my first time posting anything on github so sorry if I am doing it wrong.

Thanks!

**Comment by edannenberg** [comment]
Hi and sorry for the confusion, the documentation is still a bit lacking in that regard. Looking at the inner exception:

```
[{:type org.eclipse.jgit.errors.TransportException
   :message ssh://git@github.com/clj-jgit/clj-jgit.git: java.io.FileNotFoundException:  (No such file or directory)
   :at [org.eclipse.jgit.transport.JschConfigSessionFactory getSession JschConfigSessionFactory.java 160]}
  {:type com.jcraft.jsch.JSchException
   :message java.io.FileNotFoundException:  (No such file or directory)
   :at [com.jcraft.jsch.KeyPair load KeyPair.java 543]}     <------------------------------------- 
  {:type java.io.FileNotFoundException
   :message  (No such file or directory)
   :at [java.io.FileInputStream open0 FileInputStream.java -2]}]
```

The `with-identity/credentials` macros configure `JschConfigSessionFactory`, which is used by the underlying JGit for managing ssh connections, namely reading a user's ssh host/key information in `~/.ssh/` or from a custom location. So basically you only want to use those two macros for key based authentication, the password in this case is for your own local private key. I can see how this can be confusing though, should at the very least get clarified in the docs and also probably better handled on our end. Soon(tm).

In theory simply using a clone url like `ssh://<user>:<pwd>@<host>:22/<path-to-remote-repo>/` should do the trick for your use case, however be aware that it may not be supported by the git server. Github and Gitlab for example only allow HTTPS for keyless authentication, but the url format is the same except for the protocol part. This can be problematic/tricky when using special chars in your password, so personally I would recommend setting up key based auth.

Hope this answers your question.

**Comment by olliesweez** [comment]
Thanks for the quick response.
Unfortunately, the solution you provided did not work in my case. However, I did find a Java example online of someone using `JschConfigSessionFactory` with a basic username and password. Using your code as a baseline I was able to get it working:

```
(def jsch-factory
  (proxy [JschConfigSessionFactory] []
    (configure [hc session]
      (.setPassword session git-pw))))

(def transport-callback
  (proxy [TransportConfigCallback] []
    (configure [transport]
      (.setSshSessionFactory transport jsch-factory))))

(defn clone-cmd [uri]
  (-> (Git/cloneRepository)
      (.setURI uri)
      (.setTransportConfigCallback transport-callback)))

(defn git-clone [uri local-dir]
  (-> (clone-cmd uri)
      (.setDirectory (io/as-file local-dir))
      (.call)))
```


At first I tried getting it working with `SshSessionFactory.setInstance()` but it would hang at `cloneRepository.call()` and never terminate. I couldn't solve that problem so I ended up using `TrasportConfigCallback`. This also made it harder for me to modify and use clj-jgit/porcelain.clj since the `SshSessionFactory` has to be set before every call that requires authentication.

Thanks again for your help

**Comment by edannenberg** [comment]
Glad you worked it out, a bit surprised though that just the url didn't work. The jgit [cookbook](https://github.com/centic9/jgit-cookbook/blob/master/src/main/java/org/dstadler/jgit/porcelain/CloneRemoteRepositoryWithAuthentication.java) suggests that it should.

**Comment by edannenberg** [comment]
@olliesweez I would like to look into this closer soon however I have no server to test this with, could you give us some more details on the server you are working with? Is it a public service like GitHub or some internal setup? Thanks!

**Comment by edannenberg** [comment]
I took your feedback into account when switching to Apache Mina, the `SshSessionFactory` is now set for each call via `TrasportConfigCallback`. Let me know if you are still having issues.
