### ISSUE TITLE
Refactor porcelain.clj to keyword based arguments instead of overloads

### ISSUE THREAD

**Issue by edannenberg** [clj-jgit/clj-jgit#54]
As support for further git command options is added the overload approach currently used in `porcelain.clj` is no longer sufficient due to arity problems. (see #53 or #48) Instead of fixing and breaking the api in small chunks as needed I would propose to switch now for good and have things consistent.

As this is a fairly breaking change I'd like to gather some feedback on how to proceed. Thanks!

**Comment by edannenberg** [comment]
For me this pretty much the only blocker for a 0.9 release, which I'd like to get out of the door. Gonna wait a bit longer before I assume everyone is fine with any api breakage on my part. :P

/cc @mike706574 @daveyarwood @civa86

**Comment by daveyarwood** [comment]
You have my support :+1: 

If you want to make the API breakage especially evident, you could bump the version number to 1.0.0. That usually makes people less annoyed with the breakage, because it's not unheard of for code to break when a library's major version is bumped. Just a thought.

**Comment by edannenberg** [comment]
Sorry for the delay guys, actually did most of the refactoring months ago but got side tracked with other stuff. :disappointed:

Finished the rest of the refactoring today, as it's a fairly massive change it's living in the `1.0` branch for now. Testing/feedback would be most welcome.

Done:

* Use keyword arguments instead of fn overloads in porcelain.clj
* Feature parity with latest JGit for all implemented commands
* Implement git-revert
* Extend Resolvable protocol to support seqs of resolvables

Todo:

* Some JGit commands allow for multiple invocations of setters, i.e. `.addPath`. I added a generic helper [doseq-cmd-fn!](https://github.com/clj-jgit/clj-jgit/blob/1.0/src/clj_jgit/util.clj#L31) so users can also pass multiple values in such cases. Works but maybe not the best solution for this. I also tried a [macro](https://github.com/clj-jgit/clj-jgit/blob/1.0/src/clj_jgit/util.clj#L24) but the reflection warnings make it kinda ugly to use too.
* Some function like [git-clone-full](https://github.com/clj-jgit/clj-jgit/blob/1.0/src/clj_jgit/porcelain.clj#L348) look redundant to me, which is why I didn't bother refactor it for now. Not sure though.
* Moar tests, personally I think it should be enough to test if all possible options can be set successfully as JGit itself already has decent test suite. Thoughts?
* I copied the documentation from JGit for the most part, might be a bit too technical at some points
* Check/update project `README.md`

**Comment by daveyarwood** [comment]
Sounds like great progress to me! Thanks for finding the time to work on it.

To the point about tests, I agree that we don't need exhaustive tests if JGit already has a decent test suite.

**Comment by jaromil** [comment]
utACK, but will test soon. Have you switched using the 1.0.0 already?
However it looks very good to me, many thanks!
Just one question: can you detail the API breakage? what people will need to change?
There could be a simple section in the README.
I agree with merging.

**Comment by edannenberg** [comment]
> Have you switched using the 1.0.0 already?

Not yet, but gave it a good spin in the REPL and reviewed our code today. Looks good so far but we only use a handful of functions.

> Just one question: can you detail the API breakage? what people will need to change?

You will pretty much need to review every git call in your source and add the proper keyword args for each argument as needed. Everything else should work as before though, I tried to keep BC breakage to a minimum.

The diff for [test/porcelain.clj](https://github.com/clj-jgit/clj-jgit/commit/c5d73b602a9ea64699f642a8c6578b1741f3d40f#diff-51dee3605f28f2c63a49b37627675e32L12) is probably a good indication for required changes.

Our use case is fairly simple so I just had to change `git-checkout` and `git-clone` usage:

```
(gitp/git-clone repo-url repo-path "origin" "staging")

(gitp/git-clone repo-url :dir repo-path :branch "staging")
```

```
(gitp/git-checkout repo branch)

(gitp/git-checkout repo :name branch)
```

---

possible candidates for removal/deprecation:

[git-clone-full](https://github.com/clj-jgit/clj-jgit/blob/1.0/src/clj_jgit/porcelain.clj#L348) - this looks like it was needed when JGit wasn't quite as mature as it is now
[git-commit-amend](https://github.com/clj-jgit/clj-jgit/blob/1.0/src/clj_jgit/porcelain.clj#L431) / [git-add-and-commit](https://github.com/clj-jgit/clj-jgit/blob/1.0/src/clj_jgit/porcelain.clj#L440) - now just thin wrappers for `git-commit`

**Comment by marco-m** [comment]
+1 for a merge :-)

**Comment by edannenberg** [comment]
Did another review pass, `git-branch-list` and `git-log` now return friendlier output that should save people some common boiler plate. To make migration for existing code less painfull these functions now accept a `:jgit?` keyword arg to revert to the old behavior:

```
user=> (git-branch-list repo)
("1.0" "master" "pr/git-notes")
user=> (git-branch-list repo :jgit? true)
[#<org.eclipse.jgit.internal.storage.file.RefDirectory$LooseUnpeeled, Name: refs/heads/1.0, ObjectId: 6f2bf00d6abdca3d23e44e268d86c17623d70205> ....
```

For consistency functions like `git-blame`, that already had custom output, now also accept the `:jgit?` keyword arg but there there is no BC breakage, it just gives users the choice of working with the jgit objects directly if they choose to.

Minor stuff:

* Added missing `:date` field to `person-ident`

---

Fairly happy with the current state, just need to update the docs and maybe take another look at auth/ssh handling. `1.0.0-SNAPSHOT` is up on clojars, please give it a try.

**Comment by edannenberg** [comment]
`1.0.0-beta1` is up, please give it a try.

@dsabanin Can you tell me how to update api docs at http://clj-jgit.github.io/clj-jgit/ ?

**Comment by dsabanin** [comment]
@edannenberg I don't think it's automated, but what I did was `lein uberdoc` (I _think_, it was ages ago) and then copy the generated docs out of the source dir, switch branch to `gh-pages` and copy the files there, commit and push.

**Comment by edannenberg** [comment]
@dsabanin Yea I didn't see the `gh-pages` branch at first and assumed `lein marg` is enough in master branch. However when I tried pushing to `gh-pages` I got a permission error, can you check the project settings?

**Comment by dsabanin** [comment]
I'm not sure what's up with the permission error. If you can push to `master` on GitHub, you should be able to push to `gh-pages` as well. What's the error message you get?

**Comment by edannenberg** [comment]
Somehow my local branch had a wrong ref which prevented pushing, not sure how that happened. Was able to push after resolving that. Sorry for the noise.
