### ISSUE TITLE
NPE with porcelain/git-blame

### ISSUE THREAD

**Issue by mathpunk** [clj-jgit/clj-jgit#60]
I have a need to programmatically look at diffs and the authors that made them. I played with this library for a little bit, and I can't seem to get a BlameCommand to generate any data when I send it a `call` message. I got as far as adding a step to set the BlameCommand's diffing algorithm, but that didn't change the results. I may keep trying to debug this but I welcome any input before I put more time in.

**Comment by edannenberg** [comment]
Hi, thanks for reporting, can you give us some more information on how to reproduce the issue? This works for me:

```
(git-blame repo "README.md")
({:author
  {:name "Dario Civallero",
   :email "dario.civallero@etiqa.it",
   :timezone
   #object[sun.util.calendar.ZoneInfo 0x2bd42124 "sun.util.calendar.ZoneInfo[id=\"GMT+01:00\",offset=3600000,dstSavings=0,useDaylight=false,transitions=0,lastRule=null]"]},
  :commit
  #object[org.eclipse.jgit.revwalk.RevCommit 0xcdf22c6 "commit 6537302c73d425bdbc696ce6f421f2c49ac53833 1510165050 -----p"],
  :committer
  {:name "Erik Dannenberg",
   :email "erik.dannenberg@bbe-consulting.de",
   :timezone
   #object[sun.util.calendar.ZoneInfo 0x1f12ab02 "sun.util.calendar.ZoneInfo[id=\"GMT+01:00\",offset=3600000,dstSavings=0,useDaylight=false,transitions=0,lastRule=null]"]},
  :line 0,
  :line-contents "# clj-jgit",
  :source-path "README.md"}
```

**Comment by mathpunk** [comment]
I'm sorry, I must still be missing something. I used `load-repo` on an absolute path to my repository, and things like `git-status` give me expected results. But trying `git-blame` gets me---

```
cyclotron.repl> (git/git-blame repo ".gitignore")
IllegalArgumentException No matching method found: setFilePath for class clj_jgit.porcelain$git_blame$repo__7767  clojure.lang.Reflector.invokeMatchingMethod (Reflector.java:53)`
```
Is `repo` meant to be an instance of `org.eclipse.jgit.api.Git`? Or do I have to use some sort of get command on that object to get the intended first argument to the porcelain commands?

**Comment by edannenberg** [comment]
Yea `repo` is the JGit instance. Did you follow the steps from the ``README.md`?

```
(use 'clj-jgit.porcelain)

(def my-repo
  (:repo (git-clone-full "https://github.com/clj-jgit/clj-jgit.git" "local-folder/clj-jgit")))
```

**Comment by mathpunk** [comment]
I didn't, since I don't need to clone the repo --- I expect it to be present when my program runs. Here's the minimum to reproduce the error I'm getting:

```
(require '[clj-jgit.porcelain :as git]
         '[clojure.java.io :as io])

(def base "/home/me/my-company/dev/our-product")
(def repo (git/load-repo base))
(type repo)
;; => org.eclipse.jgit.api.Git

(def some-filename ".gitignore")
(.isFile (io/as-file (str base "/" some-filename)))
;; => true

(git/git-blame repo some-filename)
;; IllegalArgumentException No matching method found: setFilePath for class clj_jgit.porcelain$git_blame$repo__7767  clojure.lang.Reflector.invokeMatchingMethod (Reflector.java:53)
```

**Comment by mathpunk** [comment]
I better make sure I didn't break the code myself while trying to understand it, I'll check my version.

**Comment by mathpunk** [comment]
I was using some other version! Thank you for sanity checking my error so I could find the real one.
