### ISSUE TITLE
Replace jsch with apache mina

### ISSUE THREAD

**Issue by edannenberg** [clj-jgit/clj-jgit#61]
As `Jsch` is no longer developed/maintained JGit introduced an alternative based on Apache Mina in the `5.2` release. This will most likely become the default at some point as it supports modern ssh keys like `ed25519`.

Looks quite usable already however reading password encrypted ssh keys is not yet supported. Upstream Mina already has the change, might make it into the scheduled Jgit release this june.

Did some prototyping for the switch, changes:

* defaults for ssh key auth expect a standard openssh setup in `~/.ssh/`, the `with-identity` macro is no longer required in that case, it just works(tm).
* to override the defaults `(with-identity {:name "id_rsa" :key-dir "/some/path" :passphrase "xxx"} cmd)`
  * the public key is expected at `(str (:name config) ".pub")`, haven't seen an option yet to configure this easily, is this actually needed?
  * all other options for `with-identity` are no longer used and will probably be removed
  * `:name` also accepts a seq of keyfiles, default: `["id_rsa", "id_dsa", "id_ecdsa", "id_ed25519"]`, previously this could be achieved by setting `:identities`
* host key verification is enabled by default, `known_hosts` file is used as usual
  * TODO: probably should add an option to disable this, sadly not as straight forward as with Jsch, `git config http.sslVerify false` is respected though.

**Comment by jaromil** [comment]
Its quite of a breaking change for current applications, especially forcing the setup path to `~/.ssh`. Can it be implemented as an option, either at compile-time or run-time?

**Comment by jaromil** [comment]
Its quite of a breaking change for current applications, especially forcing the setup path to `~/.ssh`. Can it be implemented as an option, either at compile-time or run-time?

**Comment by edannenberg** [comment]
It's just the default, not hard coded. You can still use the `with-identity` macro to configure location, etc:

`(with-identity {:name "id_rsa" :key-dir "/some/path" :passphrase "xxx"} ...)`

**Comment by edannenberg** [comment]
The JGit june release had the Apache Mina update for encrypted keys, so I went ahead and dropped JSch completely now. See updated api docs/README.md for usage.

Tested most combinations with GitHub and our internal GitLab.

**Comment by mikroskeem** [comment]
Any news on this? `ed25519` support would be awesome
