### ISSUE TITLE
Could you do a release to capture the stuff currently on master?

### ISSUE THREAD

**Issue by morganastra** [clj-jgit/clj-jgit#62]
Hey!

So I was trying to use `git-remote-add`, and I noticed it's implemented on the current master branch, but the stable release version doesn't it them yet. For now I've just used the master SHA, but is there a possibility of doing another point release soon so people who want to use that and other functions that are on master but not the release can do so?

Cheers

**Comment by edannenberg** [comment]
Hi,

sorry for the late reply. Just pushed `1.0.0-beta1`, lots of changes, if you would rather stay on the old version until the big `1.0.0` please use `0.9.1-SNAPSHOT.`
