### ISSUE TITLE
porcelain functions don't work with `~`

### ISSUE THREAD

**Issue by saitouena** [clj-jgit/clj-jgit#66]
``` clj
(ns example
  (:require [clj-jgit.porcelain :as git]))

(def repo (git/load-repo "~/proj/clj-jgit/.git"))
(git/git-branch-list repo) ;; => ()
(def repo (git/load-repo "../clj-jgit/.git"))
(git/git-branch-list repo) ;; => ("master")
```
Maybe this is because Jgit don't accept absolute path.

If this is not a bug, note about this in README might be helpful.

**Comment by edannenberg** [comment]
`~/foo` is not really an absolute path, it only gets expanded to one by the shell (bash etc). Try `(str (System/getProperty "user.home") (File/separator) foo)` as path instead.

Parts of the docs seem to suggest that `~` is supported in paths, I'll review this once I got a few moments to spare.  If JGit supports it for its paths it probably makes sense to make things consistent on our end.

**Comment by saitouena** [comment]
> it only gets expanded to one by the shell (bash etc).

I totally misunderstood this.

I don't think clj-jgit should support `~` . Anyway thanks for your explanation!
