### ISSUE TITLE
Possible leak

### ISSUE THREAD

**Issue by icemanmelting** [clj-jgit/clj-jgit#69]
Hi, I was using your wrapper to create a backup tool for my company's code base. Since I need to use multiple repos in sequence, the memory usage was getting out of hand since the repo object is never closed. It seems that JGit constructor that sets the repoClose flag is private, and is set to false by default. I created a local commit and tested it,  It seems to have improved somehow. Also I replaced the try-finally-close with with-open, it is a try with resources for clojure. Let me know if you will allow me to create a PR.

**Comment by edannenberg** [comment]
Thanks for reporting! PR are always welcome.

**Comment by edannenberg** [comment]
Hello @icemanmelting, any news on this? If you don't have the time just let us know.

**Comment by edannenberg** [comment]
I hope you are alright @icemanmelting. Went ahead and added a fix as per your suggestion, thanks again for reporting!

**Comment by edannenberg** [comment]
1.0.1 release is now available on clojars.
