### ISSUE TITLE
`bare` repository, how to create document?

### ISSUE THREAD

**Issue by avelino** [clj-jgit/clj-jgit#73]
I created a repository with parameter `bare` and I can't create a document and commit in the repository

With jgit (java) you have to do [`RevWalk` (example here)](https://gist.github.com/porcelli/3882505), was it implemented in `clj-jgit`?

**Comment by edannenberg** [comment]
> I can't create a document and commit in the repository

That is the defining feature of a bare repository. I think you are supposed to clone a normal repo from this bare repo which you can then work with normally, then [push](https://github.com/clj-jgit/clj-jgit/blob/master/test/clj_jgit/test/porcelain.clj#L96) your work to the bare repo. 

> With jgit (java) you have to do [RevWalk (example here)](https://gist.github.com/porcelli/3882505), was it implemented in clj-jgit?

See https://github.com/clj-jgit/clj-jgit/blob/fe159662f34e738c083fb7f73a86eaecf5f8ceac/src/clj_jgit/internal.clj#L13

Hope that helps.

**Comment by avelino** [comment]
thanks for the help, I was able to implement what I needed
