### ISSUE TITLE
Feature request: support direct use of jgit's diff

### ISSUE THREAD

**Issue by KingMob** [clj-jgit/clj-jgit#75]
jgit's diff is one of the best general-purpose Java diffing libraries, and exposing it via clj-jgit would be nice. 

There's java-diff-utils, which sort of uses jgit, but is not as up-to-date, and is definitely not as easy as Clojure.

**Comment by edannenberg** [comment]
Apologies for the late reply, did you see the `changed-files-with-patch` function in the `clj-jgit.querying` ns? If so, could you describe your use case/expectations?

In any case, the majority of the code in that namespace is almost 10 years old, so probably a good idea to revisit and possibly refactor it to be on par with the `porcelain` ns.

**Comment by KingMob** [comment]
My use case is that I want to diff non-git-related things: strings, sequences, etc. In particular, I want to diff machine learning transcriptions from different providers of the same audio, and with reference transcriptions.

I'm using jgit directly, and it's not too bad, but I also wanted to suggest that there's value in exposing the diff functionality directly, if you're so inclined.

**Comment by edannenberg** [comment]
Just created a PR that adds support for diffing strings, please take a look if you got a few. I added an example for diffing lists but the aot compilation seems to mess with refreshing namespaces in the repl, so I put it behind a comment for now.

**Comment by KingMob** [comment]
Looks cool. Maybe separate the edit list creation and displaying the patch in `diff-string-formatted`? Not sure what the AOT issue, I haven't encountered it...

**Comment by edannenberg** [comment]
> Maybe separate the edit list creation and displaying the patch in diff-string-formatted?

I added `get-diff-formatter` to create a new `DiffFormatter` instance.

> Not sure what the AOT issue, I haven't encountered it.

Diffing lists works, just refreshing namespaces in the REPL won't work anymore when AOT is enabled. Looks like some issue with `gen-class` and `refresh` from `tools.namespace`. If you diff anything else besides strings I would be interested in your approach.

**Comment by KingMob** [comment]
In transcription, the dominant metric is the word error rate (WER), the word edit distance divided by the total number of words, so we tend to be focused on words, not characters. 

Given the difference between pronunciation and spelling (at least in English, not true for all langs), a word with more character errors might actually be a better/worse/same transcription than another with fewer character errors.

Here's a made-up example: consider the phrase "book, it" in the middle of a reference transcription. If we go by letter-based edit distance, the phrase "boo kit" (a Halloween tool?) has a lower Levenshtein distance than "bucket" (3 vs 5), but "bucket" is a much more plausible utterance than "boo kit". A system trained with letter-based distances might erroneously learn that "boo kit" is better in this case.

It's a bit contrived, but a word-based edit distance will compute an edit distance of 2 for both of them, so it's not as biased.

My data typically looks like a vector or seq of pre-inverse-normalized words. I.e., split on whitespace, no capitalization or  punctuation, "two hundred dollars" instead of "$200". Something of like `["i" "owe" "john" "twenty" "bucks"]`

**Comment by edannenberg** [comment]
I see, thanks. How about the technical approach, did you also go with `gen-class` or something else? Would the example for diffing seqs in the PR be useful to you?

**Comment by KingMob** [comment]
I'm afraid I haven't looked at any PRs, and sadly, the business idea I needed this for didn't pan out, so I'm no longer diffing transcriptions.

I _can_ say I wasn't using gen-class for anything. AOT can lead to annoying classpath bugs IME, so I avoid it unless absolutely necessary.

**Comment by edannenberg** [comment]
Sorry to hear that. 

> I can say I wasn't using gen-class for anything. AOT can lead to annoying classpath bugs IME, so I avoid it unless absolutely necessary.

Yea, which is why I asked what you did go with. ;) Pure Java classes? Proxy and reify didn't work out for me as `org.eclipse.jgit.diff.Sequence` needs a new method to provide it's contents to the comparator.

**Comment by KingMob** [comment]
Oh, the library I ended up using was https://github.com/java-diff-utils/java-diff-utils. It met my needs: support for non-strings and the histogram diff algorithm.

**Comment by edannenberg** [comment]
Sorry for the delay, got side-tracked by RL. I finished the open work I sill had lying around for this (git-diff command) and will most likely leave this as is for now.
